version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: handmade_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: handmade_shop
      MYSQL_USER: handmade_user
      MYSQL_PASSWORD: handmade_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer:latest
    container_name: handmade_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
